### ISSUE TITLE
Add a build pipeline

### ISSUE THREAD

**Issue by iamandylamb** [iamandylamb/ExplicitMapper#7]
I'd like:
* The tests to be run on PRs.

**Comment by colin-gourlay** [comment]
I'd be interested in helping out with this.

Any thoughts on what direction you want to go with this? I've a bit of experience with Cake and AppVeyor if that interests.

**Comment by feelthesource** [comment]
Thanks Colin! I'm happy to take your recommendation regarding the approach.

**Comment by iamandylamb** [comment]
@cgourlay, [GitHub Actions](https://github.com/iamandylamb/ExplicitMapper/actions/new) might help?

**Comment by colin-gourlay** [comment]
@iamandylamb Thanks for pointing me in the direction of the GitHub Actions - wasn't aware of these until now! [Cake ](https://cakebuild.net/) has moved on a fair bit since I last looked at it, so I found myself looking at [Nuke](https://nuke.build/) as an 'alternative'. However, GitHub Actions look like a really good fit so I'll look into these.

**Comment by colin-gourlay** [comment]
@iamandylamb Success of sorts - The GitHub Action (GA) fails because the code will not compile - this is good because it demonstrates its doing its job. I'm not sure on the course of action though. The compilation fails due to `Example.Castle.Windsor.csproj` & `Example.Autofac.csproj` targeting `<TargetFramework>net4.6.1</TargetFramework>`. Should I alter the GitHub Action accordingly or  should these projects be targeting core 3.x?

**Comment by iamandylamb** [comment]
Great stuff @cgourlay. I targeted .NET Framework specifically for those projects because I wanted to demonstrate the library works in Core and Framework and in Core I think Microsoft.Extensions.DependencyInjection would be the 'go-to' DI framework. When I run `dotnet build` locally it all compiles OK?

**Comment by feelthesource** [comment]
Maybe exclude the 'example' projects from the build for now? Just to keep it simple.

**Comment by iamandylamb** [comment]
@cgourlay, I removed the .NET Framework projects from the 'Release' configuration and updated the Test project to use .NET Core. Your PR should work now?

**Comment by iamandylamb** [comment]
I removed the 'and release pipeline' part from this issue and created a separate issue for it (#14)
